export const portfolioItems = [
  {
    title: 'MEGA Family',
    description: 'Мобильное приложение Mega Family на платформах iOS и Android',
    backgroundColor: 'bg-[#bdeffc]',
    type: 'Приложения',
    id: 1,
  },
  {
    title: 'Tvoy.kz',
    description: 'Мобильное приложение для заказа товаров из сети супермаркетов Small',
    backgroundColor: 'bg-[#ffc9f9]',
    type: 'Сервисы',
    id: 2,
  },
  {
    title: 'Ecuador',
    description: 'Мобильное приложение и админ панель для Министерство Эквадоры ',
    backgroundColor: 'bg-[#ffcccf]',
    type: 'Сервисы',
    id: 3,
  },
  {
    title: 'Drop Shop',
    description: 'Разработка интернет-магазина для сети магазинов техники"',
    backgroundColor: 'bg-[#c4f2e1]',
    type: 'Интернет-Магазины',
    id: 4,
  },
  {
    title: 'QOS',
    description: 'Мобильное приложение для продвижения Q-POP индустрии',
    backgroundColor: 'bg-[#ffbffc]',
    type: 'Приложения',
    id: 5,
  },
  {
    title: 'Gippo',
    description: 'Разработка интернет-магазина для сети быстрого питания',
    backgroundColor: 'bg-[#fcf1c2]',
    type: 'Промо',
    id: 6,
  },
  {
    title: 'Masa Media',
    description: 'Новосной портал о политике и не только',
    backgroundColor: 'bg-[#d1baff]',
    type: 'Промо',
    id: 7,
  },
  {
    title: 'Eliks',
    description: 'Сайт для пекарни особой выпечки',
    backgroundColor: 'bg-[#9fd5e3]',
    type: 'Промо',
    id: 8,
  },
  {
    title: 'Sony',
    description: 'Мобильное приложение Sony',
    backgroundColor: 'bg-[#bff8ff]',
    type: 'Корпоративные',
    id: 9,
  },
  {
    title: '31 канал',
    description: 'Корпоративный сайт 31-канала',
    backgroundColor: 'bg-[#ffc9db]',
    type: 'Корпоративные',
    id: 10,
  },
];
